import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
import { NextResponse } from "next/server";

const products = [
  {
    name: "Essential Cotton Crew Tee",
    slug: "essential-cotton-crew-tee",
    description: "Crafted from 100% organic Pima cotton, this crew neck tee is the foundation of every considered wardrobe. Pre-washed for a lived-in softness from the first wear, with a refined fit that sits perfectly between slim and regular.",
    price: 2490,
    mrp: 3490,
    category: "T-Shirts",
    brand: "MAISON Essentials",
    sizes: '["XS","S","M","L","XL"]',
    colors: '["#FFFFFF","#111111","#4D5B47","#B79B7B"]',
    images: '["/images/products/product-2.png","/images/products/product-2.png"]',
    rating: 4.6,
    reviewCount: 128,
    stock: 150,
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isFlashDeal: false,
    discount: 29,
    material: "100% Organic Pima Cotton, 180 GSM",
    care: "Machine wash cold, tumble dry low",
    tags: "basics,essential,cotton,crew-neck",
  },
  {
    name: "Tailored Navy Wool Blazer",
    slug: "tailored-navy-wool-blazer",
    description: "A masterclass in understated tailoring. This single-breasted blazer is cut from Italian wool with a natural shoulder and half-canvas construction. The kind of piece that elevates everything it touches.",
    price: 12990,
    mrp: 18990,
    category: "Blazers",
    brand: "MAISON Tailored",
    sizes: '["S","M","L","XL"]',
    colors: '["#1a2744","#111111","#4D5B47"]',
    images: '["/images/products/product-6.png","/images/products/product-6.png"]',
    rating: 4.8,
    reviewCount: 67,
    stock: 45,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isFlashDeal: false,
    discount: 32,
    material: "100% Italian Wool, Half-canvas construction",
    care: "Dry clean only",
    tags: "blazer,wool,tailored,formal",
  },
  {
    name: "Premium Raw Selvedge Denim",
    slug: "premium-raw-selvedge-denim",
    description: "Japanese selvedge denim from the famed Kuroki mills. These jeans will develop a unique patina over time, becoming distinctly yours. A straight fit with a mid-rise that works with everything.",
    price: 6990,
    mrp: 8990,
    category: "Jeans",
    brand: "MAISON Denim",
    sizes: '["28","30","32","34","36"]',
    colors: '["#1a2332","#111111"]',
    images: '["/images/products/product-3.png","/images/products/product-3.png"]',
    rating: 4.7,
    reviewCount: 203,
    stock: 80,
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isFlashDeal: true,
    discount: 22,
    material: "14oz Japanese Selvedge Denim, 100% Cotton",
    care: "Wash inside out, cold water, hang dry",
    tags: "denim,jeans,selvedge,japanese,raw",
  },
  {
    name: "Cashmere-Blend Crew Sweater",
    slug: "cashmere-blend-crew-sweater",
    description: "An indulgent blend of Mongolian cashmere and fine merino wool. This crew neck sweater delivers extraordinary softness with remarkable durability. The kind of luxury you feel against your skin.",
    price: 8990,
    mrp: 12990,
    category: "Sweaters",
    brand: "MAISON Knitwear",
    sizes: '["XS","S","M","L","XL","XXL"]',
    colors: '["#D4C4B0","#F5F0E8","#111111","#4D5B47"]',
    images: '["/images/products/product-4.png","/images/products/product-4.png"]',
    rating: 4.9,
    reviewCount: 156,
    stock: 60,
    isFeatured: true,
    isNew: true,
    isTrending: false,
    isBestSeller: true,
    isFlashDeal: false,
    discount: 31,
    material: "70% Mongolian Cashmere, 30% Fine Merino Wool",
    care: "Hand wash cold, lay flat to dry",
    tags: "cashmere,sweater,knitwear,luxury",
  },
  {
    name: "Leather Chelsea Boots",
    slug: "leather-chelsea-boots",
    description: "Handcrafted from full-grain calfskin leather with a Goodyear-welted sole. These Chelsea boots are built to age beautifully and last for years. A timeless silhouette refined for the modern wardrobe.",
    price: 15990,
    mrp: 21990,
    category: "Footwear",
    brand: "MAISON Footwear",
    sizes: '["7","8","9","10","11","12"]',
    colors: '["#8B6914","#111111","#5C3D2E"]',
    images: '["/images/products/product-5.png","/images/products/product-5.png"]',
    rating: 4.8,
    reviewCount: 89,
    stock: 35,
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isFlashDeal: false,
    discount: 27,
    material: "Full-grain Calfskin Leather, Goodyear Welt, Leather Sole",
    care: "Use leather conditioner regularly, store with shoe trees",
    tags: "boots,chelsea,leather,footwear,handcrafted",
  },
  {
    name: "Silk-Blend Pocket Square",
    slug: "silk-blend-pocket-square",
    description: "An exquisite pocket square in deep olive, hand-rolled edges, woven from a sumptuous silk-wool blend. The finishing touch that elevates any blazer or suit.",
    price: 1990,
    mrp: 2490,
    category: "Accessories",
    brand: "MAISON Accessories",
    sizes: '["ONE SIZE"]',
    colors: '["#4D5B47","#B79B7B","#5C2D2D","#1a2744"]',
    images: '["/images/products/product-7.png","/images/products/product-7.png"]',
    rating: 4.5,
    reviewCount: 74,
    stock: 200,
    isFeatured: false,
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isFlashDeal: true,
    discount: 20,
    material: "65% Silk, 35% Wool",
    care: "Dry clean only",
    tags: "accessories,pocket-square,silk",
  },
  {
    name: "Minimal Leather Sneakers",
    slug: "minimal-leather-sneakers",
    description: "Clean lines meet exceptional craftsmanship. These sneakers are constructed from premium white leather with a Margom rubber sole — the gold standard in luxury sneaker-making. Zero logos, maximum quality.",
    price: 9990,
    mrp: 13990,
    category: "Footwear",
    brand: "MAISON Footwear",
    sizes: '["7","8","9","10","11","12"]',
    colors: '["#FFFFFF","#F5F0E8","#111111"]',
    images: '["/images/products/product-8.png","/images/products/product-8.png"]',
    rating: 4.7,
    reviewCount: 312,
    stock: 90,
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isFlashDeal: false,
    discount: 29,
    material: "Full-grain Italian Leather, Margom Rubber Sole",
    care: "Use leather cleaner, store with shoe trees",
    tags: "sneakers,leather,minimal,white",
  },
  {
    name: "Tailored Wool Trousers",
    slug: "tailored-wool-trousers",
    description: "Impeccably tailored from premium wool with a hint of stretch for all-day comfort. A clean, tapered leg with a mid-rise that pairs effortlessly with blazers and knitwear alike.",
    price: 5990,
    mrp: 7990,
    category: "Trousers",
    brand: "MAISON Tailored",
    sizes: '["28","30","32","34","36"]',
    colors: '["#111111","#3a3a3a","#4D5B47","#1a2744"]',
    images: '["/images/products/product-9.png","/images/products/product-9.png"]',
    rating: 4.6,
    reviewCount: 145,
    stock: 70,
    isFeatured: false,
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isFlashDeal: false,
    discount: 25,
    material: "97% Wool, 3% Elastane",
    care: "Dry clean recommended",
    tags: "trousers,wool,tailored,formal",
  },
  {
    name: "Merino Wool Overcoat",
    slug: "merino-wool-overcoat",
    description: "A substantial overcoat crafted from double-faced Italian merino wool. The clean, unstructured silhouette provides warmth without bulk. An investment piece that transcends seasons and trends.",
    price: 19990,
    mrp: 28990,
    category: "Outerwear",
    brand: "MAISON Outerwear",
    sizes: '["S","M","L","XL"]',
    colors: '["#6B6B6B","#111111","#4D5B47","#D4C4B0"]',
    images: '["/images/products/product-10.png","/images/products/product-10.png"]',
    rating: 4.9,
    reviewCount: 58,
    stock: 25,
    isFeatured: true,
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isFlashDeal: false,
    discount: 31,
    material: "100% Italian Merino Wool, Double-faced",
    care: "Dry clean only",
    tags: "overcoat,wool,outerwear,winter",
  },
  {
    name: "Linen Button-Down Shirt",
    slug: "linen-button-down-shirt",
    description: "Effortless luxury in pure European flax linen. This button-down features a relaxed yet refined fit, mother-of-pearl buttons, and a soft, lived-in hand feel that only improves with wear.",
    price: 3990,
    mrp: 5490,
    category: "Shirts",
    brand: "MAISON Essentials",
    sizes: '["XS","S","M","L","XL"]',
    colors: '["#F5F0E8","#FFFFFF","#B7C4B5","#D4C4B0"]',
    images: '["/images/products/product-11.png","/images/products/product-11.png"]',
    rating: 4.5,
    reviewCount: 198,
    stock: 110,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isFlashDeal: true,
    discount: 27,
    material: "100% European Flax Linen",
    care: "Machine wash gentle, hang dry",
    tags: "shirt,linen,summer,casual",
  },
  {
    name: "Leather Crossbody Bag",
    slug: "leather-crossbody-bag",
    description: "A study in considered minimalism. This crossbody bag is handcrafted from vegetable-tanned leather that develops a rich patina over time. One main compartment, one interior pocket. Nothing more, nothing less.",
    price: 8990,
    mrp: 12990,
    category: "Bags",
    brand: "MAISON Leather",
    sizes: '["ONE SIZE"]',
    colors: '["#111111","#5C3D2E","#8B6914"]',
    images: '["/images/products/product-1.png","/images/products/product-1.png"]',
    rating: 4.7,
    reviewCount: 92,
    stock: 40,
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isBestSeller: false,
    isFlashDeal: false,
    discount: 31,
    material: "Full-grain Vegetable-tanned Leather, Cotton Lining",
    care: "Apply leather conditioner every 3-6 months",
    tags: "bag,leather,crossbody,accessories",
  },
  {
    name: "Swiss Automatic Dress Watch",
    slug: "swiss-automatic-dress-watch",
    description: "Housing a Swiss automatic movement beneath a sapphire crystal, this dress watch embodies quiet luxury. The 39mm case is crafted from 316L surgical steel with a hand-finished dial. A lifetime companion.",
    price: 24990,
    mrp: 34990,
    category: "Accessories",
    brand: "MAISON Timepieces",
    sizes: '["ONE SIZE"]',
    colors: '["#111111","#5C3D2E","#3a3a3a"]',
    images: '["/images/products/product-12.png","/images/products/product-12.png"]',
    rating: 4.9,
    reviewCount: 43,
    stock: 15,
    isFeatured: true,
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isFlashDeal: false,
    discount: 29,
    material: "316L Surgical Steel, Swiss Automatic Movement, Sapphire Crystal",
    care: "Service every 3-5 years",
    tags: "watch,swiss,automatic,accessories,luxury",
  },
  {
    name: "Relaxed Fit Oxford Shirt",
    slug: "relaxed-fit-oxford-shirt",
    description: "A modern take on the classic Oxford button-down. Cut from premium long-staple cotton with a relaxed, contemporary fit. The kind of shirt that works equally well with tailoring or denim.",
    price: 3490,
    mrp: 4490,
    category: "Shirts",
    brand: "MAISON Essentials",
    sizes: '["XS","S","M","L","XL"]',
    colors: '["#FFFFFF","#E8E4DE","#1a2744","#B7C4B5"]',
    images: '["/images/products/product-2.png","/images/products/product-6.png"]',
    rating: 4.4,
    reviewCount: 267,
    stock: 130,
    isFeatured: false,
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isFlashDeal: false,
    discount: 22,
    material: "100% Long-staple Cotton Oxford, 200 GSM",
    care: "Machine wash warm, iron medium heat",
    tags: "shirt,oxford,cotton,casual",
  },
  {
    name: "Heavyweight Cotton Hoodie",
    slug: "heavyweight-cotton-hoodie",
    description: "Built from 400GSM French terry cotton, this hoodie has real substance. Features a kangaroo pocket, ribbed cuffs, and a lined drawcord hood. Garment-dyed for a rich, broken-in appearance.",
    price: 4990,
    mrp: 6490,
    category: "Sweaters",
    brand: "MAISON Essentials",
    sizes: '["S","M","L","XL","XXL"]',
    colors: '["#3a3a3a","#4D5B47","#D4C4B0","#111111"]',
    images: '["/images/products/product-4.png","/images/products/product-10.png"]',
    rating: 4.6,
    reviewCount: 341,
    stock: 95,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isFlashDeal: true,
    discount: 23,
    material: "100% French Terry Cotton, 400 GSM",
    care: "Machine wash cold, tumble dry low",
    tags: "hoodie,cotton,heavyweight,casual",
  },
  {
    name: "Leather Belt — Cognac",
    slug: "leather-belt-cognac",
    description: "Cut from a single piece of full-grain bridle leather with a solid brass buckle. This belt will develop a beautiful patina unique to you. 35mm width — the perfect proportion for any trouser.",
    price: 2990,
    mrp: 3990,
    category: "Accessories",
    brand: "MAISON Leather",
    sizes: '["32","34","36","38"]',
    colors: '["#8B6914","#111111","#5C3D2E"]',
    images: '["/images/products/product-5.png","/images/products/product-12.png"]',
    rating: 4.5,
    reviewCount: 178,
    stock: 120,
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isFlashDeal: false,
    discount: 25,
    material: "Full-grain Bridle Leather, Solid Brass Hardware",
    care: "Apply leather conditioner periodically",
    tags: "belt,leather,accessories,brass",
  },
  {
    name: "Pleated Wide-Leg Trousers",
    slug: "pleated-wide-leg-trousers",
    description: "A relaxed wide-leg trouser with double pleats, cut from a substantial cotton-linen blend. The high rise and clean lines create an effortlessly elegant silhouette.",
    price: 4490,
    mrp: 5990,
    category: "Trousers",
    brand: "MAISON Tailored",
    sizes: '["28","30","32","34","36"]',
    colors: '["#F5F0E8","#3a3a3a","#111111","#4D5B47"]',
    images: '["/images/products/product-9.png","/images/products/product-3.png"]',
    rating: 4.3,
    reviewCount: 89,
    stock: 65,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isFlashDeal: false,
    discount: 25,
    material: "55% Linen, 45% Cotton",
    care: "Machine wash gentle, hang dry, iron while damp",
    tags: "trousers,pleated,wide-leg,linen",
  },
];

const categories = [
  { name: "T-Shirts", slug: "t-shirts", sortOrder: 1 },
  { name: "Shirts", slug: "shirts", sortOrder: 2 },
  { name: "Blazers", slug: "blazers", sortOrder: 3 },
  { name: "Sweaters", slug: "sweaters", sortOrder: 4 },
  { name: "Jeans", slug: "jeans", sortOrder: 5 },
  { name: "Trousers", slug: "trousers", sortOrder: 6 },
  { name: "Outerwear", slug: "outerwear", sortOrder: 7 },
  { name: "Footwear", slug: "footwear", sortOrder: 8 },
  { name: "Bags", slug: "bags", sortOrder: 9 },
  { name: "Accessories", slug: "accessories", sortOrder: 10 },
];

const brands = [
  { name: "MAISON Essentials", slug: "maison-essentials" },
  { name: "MAISON Tailored", slug: "maison-tailored" },
  { name: "MAISON Denim", slug: "maison-denim" },
  { name: "MAISON Knitwear", slug: "maison-knitwear" },
  { name: "MAISON Footwear", slug: "maison-footwear" },
  { name: "MAISON Outerwear", slug: "maison-outerwear" },
  { name: "MAISON Accessories", slug: "maison-accessories" },
  { name: "MAISON Leather", slug: "maison-leather" },
  { name: "MAISON Timepieces", slug: "maison-timepieces" },
];

const reviews = [
  { productId: 1, userName: "Arjun M.", rating: 5, title: "Perfect everyday tee", comment: "The quality is exceptional. I've washed these dozens of times and they still look brand new." },
  { productId: 1, userName: "Priya S.", rating: 4, title: "Great fit", comment: "Love the fit and fabric. Slightly long but that's my preference." },
  { productId: 2, userName: "Vikram K.", rating: 5, title: "Investment piece", comment: "The construction quality is on par with brands charging 3x the price. Beautiful fabric." },
  { productId: 3, userName: "Rahul D.", rating: 5, title: "Best jeans I own", comment: "The raw denim is incredible. Starting to see beautiful fading patterns after 3 months." },
  { productId: 4, userName: "Ananya R.", rating: 5, title: "Incredible softness", comment: "This cashmere is the real deal. Worth every rupee." },
  { productId: 5, userName: "Karan S.", rating: 5, title: "Build quality is insane", comment: "Goodyear welt, full-grain leather... these will last a decade." },
  { productId: 7, userName: "Nikhil P.", rating: 4, title: "Clean and minimal", comment: "Exactly what I was looking for. No logos, just quality." },
  { productId: 9, userName: "Dev T.", rating: 5, title: "Seasonless elegance", comment: "Wore it through winter and spring. Perfect weight and drape." },
  { productId: 10, userName: "Meera J.", rating: 5, title: "Summer essential", comment: "The linen gets softer with every wash. Beautiful texture." },
  { productId: 12, userName: "Aditya N.", rating: 5, title: "Horological excellence", comment: "The movement is smooth, the finishing is impeccable. A proper watch." },
  { productId: 6, userName: "Sanya K.", rating: 4, title: "Beautiful accessory", comment: "The silk-wool blend has a wonderful hand feel. Adds a refined touch." },
  { productId: 8, userName: "Rohan M.", rating: 5, title: "The only bag I need", comment: "The leather quality is outstanding. Already developing a gorgeous patina." },
];

const coupons = [
  { code: "WELCOME20", discount: 20, type: "percent", minOrder: 3000, maxUses: 1000, expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString() },
  { code: "FLAT1000", discount: 1000, type: "fixed", minOrder: 5000, maxUses: 500, expiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString() },
  { code: "MAISON30", discount: 30, type: "percent", minOrder: 10000, maxUses: 200, expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() },
];

export async function POST() {
  try {
    try {
      await requireAdmin();
    } catch (e: any) {
      if (e.message === 'Unauthorized') {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
      }
      if (e.message === 'Forbidden') {
        return NextResponse.json({ error: 'Admin access required' }, { status: 403 });
      }
      throw e;
    }
    // Clear existing data
    await db.orderItem.deleteMany();
    await db.order.deleteMany();
    await db.review.deleteMany();
    await db.wishlistItem.deleteMany();
    await db.product.deleteMany();
    await db.category.deleteMany();
    await db.brand.deleteMany();
    await db.coupon.deleteMany();

    // Seed categories
    const createdCategories = {};
    for (const cat of categories) {
      const created = await db.category.create({ data: cat });
      createdCategories[cat.name] = created.id;
    }

    // Seed brands
    const createdBrands = {};
    for (const brand of brands) {
      const created = await db.brand.create({ data: brand });
      createdBrands[brand.name] = created.id;
    }

    // Seed products
    for (const product of products) {
      await db.product.create({
        data: {
          ...product,
          categoryId: createdCategories[product.category] || null,
          brandId: createdBrands[product.brand] || null,
        },
      });
    }

    // Seed reviews
    for (const review of reviews) {
      const product = await db.product.findFirst({ skip: review.productId - 1 });
      if (product) {
        await db.review.create({
          data: { ...review, productId: product.id },
        });
      }
    }

    // Seed coupons
    for (const coupon of coupons) {
      await db.coupon.create({ data: coupon });
    }

    return NextResponse.json({ success: true, message: "Database seeded successfully" });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ success: false, error: "Failed to seed database" }, { status: 500 });
  }
}